//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDataModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public Author()
        {
            this.BooksAuthors = new HashSet<BooksAuthor>();
        }
    
        public int AuthorID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<BooksAuthor> BooksAuthors { get; set; }
    }
}
