//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDataModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookTransaction
    {
        public int TransactionID { get; set; }
        public string ISBN { get; set; }
        public int MemberShipNumber { get; set; }
        public int LibrarianID { get; set; }
        public System.DateTime BorrowedDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public string Status { get; set; }
        public decimal FineAmount { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Librarian Librarian { get; set; }
        public virtual MemberShip MemberShip { get; set; }
    }
}
