//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDataModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksAtLibrary
    {
        public int LibraryID { get; set; }
        public string ISBN { get; set; }
        public int NumberOfCopies { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Library Library { get; set; }
    }
}
