//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDataModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library
    {
        public Library()
        {
            this.BooksAtLibraries = new HashSet<BooksAtLibrary>();
            this.Librarians = new HashSet<Librarian>();
            this.MemberShips = new HashSet<MemberShip>();
        }
    
        public int LibraryID { get; set; }
        public string Name { get; set; }
        public int AddressID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<BooksAtLibrary> BooksAtLibraries { get; set; }
        public virtual ICollection<Librarian> Librarians { get; set; }
        public virtual ICollection<MemberShip> MemberShips { get; set; }
    }
}
