//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDataModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberShip
    {
        public MemberShip()
        {
            this.BookTransactions = new HashSet<BookTransaction>();
            this.CustomerMemberShips = new HashSet<CustomerMemberShip>();
        }
    
        public int MemberShipNumber { get; set; }
        public int MemberShipTypeId { get; set; }
        public int LibraryID { get; set; }
        public System.DateTime RegisteredDate { get; set; }
        public System.DateTime RenewalDate { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<BookTransaction> BookTransactions { get; set; }
        public virtual ICollection<CustomerMemberShip> CustomerMemberShips { get; set; }
        public virtual Library Library { get; set; }
        public virtual MemberShipType MemberShipType { get; set; }
    }
}
