//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDataModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public UserLogin()
        {
            this.Customers = new HashSet<Customer>();
            this.Librarians = new HashSet<Librarian>();
        }
    
        public string UserID { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Librarian> Librarians { get; set; }
    }
}
