//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksAuthor
    {
        public string ISBN { get; set; }
        public int AuthorID { get; set; }
        public int AuthorOrdinal { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Book Book { get; set; }
    }
}
