//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberShip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberShip()
        {
            this.BookTransactions = new HashSet<BookTransaction>();
            this.CustomerMemberShips = new HashSet<CustomerMemberShip>();
        }
    
        public int MemberShipNumber { get; set; }
        public int MemberShipTypeId { get; set; }
        public int LibraryID { get; set; }
        public System.DateTime RegisteredDate { get; set; }
        public System.DateTime RenewalDate { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookTransaction> BookTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerMemberShip> CustomerMemberShips { get; set; }
        public virtual Library Library { get; set; }
        public virtual MemberShipType MemberShipType { get; set; }
    }
}
